name: gread
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  http: ^1.1.0
  get: 4.6.6
  form_validator: ^2.1.1
  flutter: 
    sdk: flutter
  url_strategy: ^0.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

